"""Initial database structure

Revision ID: 1c9945279bf2
Revises: 
Create Date: 2024-08-04 15:06:28.464111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9945279bf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=False),
                    sa.Column('password_hash', sa.String(length=64), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), server_default=sa.text("'0'"), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('photo',
                    sa.Column('id', sa.String(length=150), nullable=False),
                    sa.Column('image_blob', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('tags', sa.String(length=100), nullable=True),
                    sa.Column('image_id', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['image_id'], ['photo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_category_image_id'), 'category', ['image_id'], unique=False)
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
                    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('image_id', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['image_id'], ['photo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_image_id'), 'products', ['image_id'], unique=False)
    op.create_index('name', 'products', ['name', 'description'], unique=False)
    op.create_table('orders',
                    sa.Column('id', sa.String(length=150), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['user_id'], ['customers.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('name', table_name='products')
    op.drop_index(op.f('ix_products_image_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_category_image_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('photo')
    op.drop_table('customers')
    # ### end Alembic commands ###
